name: agri_gestion_app
description: "Une application de gestion agricole pour les petits exploitants au Gabon"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  supabase_flutter: ^2.3.1
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  lottie: ^2.7.0
  flutter_animate: ^4.5.0
  fl_chart: ^0.66.0
  get_storage: ^2.1.1
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  intl: ^0.19.0
  uuid: ^4.2.2
  pdf: ^3.10.7
  excel: ^4.0.2
  path_provider: ^2.1.2
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/ 